name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-demo:
    strategy:
      fail-fast: true
      matrix:
        rust-target:
          [aarch64-apple-darwin, x86_64-apple-darwin, x86_64-apple-ios-macabi]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        name: Install Rust
        run: |
          rustup update
          rustup toolchain install nightly
          rustup component add rust-src --toolchain nightly

      - shell: bash
        name: ls ~/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/
        run: |
          ls -l ~/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/

      - shell: bash
        name: build default debug (x86_64-apple-ios-macabi) using nightly
        run: |
          cargo +nightly build -Z build-std --target ${{ matrix.rust-target }}
