name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        name: Install Rust
        run: |
          rustup update
          rustup toolchain install nightly
          rustup component add rust-src --toolchain nightly
      - shell: bash
        name: build default debug (aarch64-apple-darwin) using nightly
        run: |
          cargo +nightly build -Z build-std --target aarch64-apple-darwin
      - shell: bash
        name: build default debug (x86_64-apple-darwin) using nightly
        run: |
          cargo +nightly build -Z build-std --target x86_64-apple-darwin
      - shell: bash
        name: build default debug (x86_64-apple-ios-macabi) using nightly
        run: |
          cargo +nightly build -Z build-std  --target x86_64-apple-ios-macabi
